name: Build & Deploy

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install dependencies & build
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Deploy to Cloudflare
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "🔵 Deploying to production"
            npx wrangler deploy
          else
            echo "🟡 Deploying to preview environment for branch '${{ github.ref_name }}'"
            npx wrangler versions upload
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
